# Generated by Django 4.1.2 on 2022-11-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("season", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalseason",
            name="viewed",
        ),
        migrations.RemoveField(
            model_name="season",
            name="viewed",
        ),
    ]
