# Generated by Django 4.1.2 on 2022-11-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("season", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalseason",
            name="viewed",
            field=models.BooleanField(default=False, verbose_name="Visto"),
        ),
        migrations.AddField(
            model_name="season",
            name="viewed",
            field=models.BooleanField(default=False, verbose_name="Visto"),
        ),
    ]
