# Generated by Django 4.1.2 on 2022-11-19 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("season", "0001_initial"),
        ("playlist", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoplaylist",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="season.season"
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.provider"
            ),
        ),
    ]
