# Generated by Django 4.1.2 on 2022-11-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0002_rename_usuario_historicalplaylist_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalplaylist",
            name="viewed",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="viewed",
        ),
    ]
