# Generated by Django 4.1.2 on 2022-10-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvideo",
            name="active",
        ),
        migrations.RemoveField(
            model_name="video",
            name="active",
        ),
    ]
