# Generated by Django 4.1.2 on 2022-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_remove_historicalvideo_active_remove_video_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvideo",
            name="chapters",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Capitulos"
            ),
        ),
        migrations.AddField(
            model_name="historicalvideo",
            name="number_season",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Temporada"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="chapters",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Capitulos"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="number_season",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Temporada"
            ),
        ),
    ]
