# Generated by Django 4.1.2 on 2022-11-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_historicalvideo_chapters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvideo",
            name="viewed",
            field=models.BooleanField(default=False, verbose_name="Vista"),
        ),
        migrations.AddField(
            model_name="video",
            name="viewed",
            field=models.BooleanField(default=False, verbose_name="Vista"),
        ),
    ]
