# Generated by Django 4.1.2 on 2022-11-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_historicalvideo_viewed_video_viewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvideo",
            name="chapters",
            field=models.SmallIntegerField(default=0, verbose_name="Capitulos"),
        ),
        migrations.AlterField(
            model_name="historicalvideo",
            name="number_season",
            field=models.SmallIntegerField(default=0, verbose_name="Temporada"),
        ),
        migrations.AlterField(
            model_name="video",
            name="chapters",
            field=models.SmallIntegerField(default=0, verbose_name="Capitulos"),
        ),
        migrations.AlterField(
            model_name="video",
            name="number_season",
            field=models.SmallIntegerField(default=0, verbose_name="Temporada"),
        ),
    ]
